# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

#- name: Gradle Wrapper Validation
  # You may pin to the exact commit or the version.
  # uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
 # uses: gradle/wrapper-validation-action@v1.0.4
  #with:
    # Minimum expected wrapper JAR files
   # min-wrapper-count: # optional, default is 1
    # Allow snapshot Gradle versions
    #allow-snapshots: # optional, default is false
    # Allow arbitrary checksums, comma separated
    #allow-checksums: # optional, default is 
    
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: sudo chmod 755 gradlew
    - name: Build with Gradle
      run: ./gradlew build
